version: '3'

dotenv: ['.env']

tasks:
  run:
    cmds:
      - docker run
          -e MARIADB_RANDOM_ROOT_PASSWORD=true
          -e MARIADB_DATABASE=$DB_NAME
          -e MARIADB_USER=$DB_USER
          -e MARIADB_PASSWORD=$DB_PASSWORD
          -p $DB_PORT:3306
          -d mariadb
          > .CONTAINER_ID

  bash:
    cmds:
      - docker container exec -it $(cat .CONTAINER_ID)
          mariadb -u $DB_USER -p$DB_PASSWORD $DB_NAME

  destroy:
    cmds:
      - docker container rm -f $(cat .CONTAINER_ID) > /dev/null
      - rm .CONTAINER_ID
