name: Deploy
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to dokku - main
        uses: dokku/github-action@master
        with:
          git_push_flags: --force
          git_remote_url: 'ssh://dokku@hcmkt.dev:22/skydiving-main'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to dokku - form
        uses: dokku/github-action@master
        with:
          git_push_flags: --force
          git_remote_url: 'ssh://dokku@hcmkt.dev:22/skydiving-form'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
